name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup local env
        run:
          sudo apt update && sudo apt upgrade && sudo apt install curl

      - name: Install rust and Cargo
        run:
          curl https://sh.rustup.rs -sSf | bash -s -- -y

      - name: Install mdbook
        run: |
          cargo install mdbook
          cargo install mdbook-mermaid

      # - name: Setup mdBook
      #   uses: peaceiris/actions-mdbook@v1
      #   with:
      #     mdbook-version: '0.4.30'

      - name: Build mdbook
        run: mdbook build

      - name: Add mermaid to book directory
        run: mdbook-mermaid install ./book/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
